[general]
	#The Application ID of the Discord App to use. Replace this with your client id from the discord dashboard to change the name of the app
	applicationID = 1105655278860505129
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen. ONLY AVAILABLE WHEN CLOTH CONFIG IS INSTALLED!
	configScreen = true
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 18

[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "Optimized Oasis Lite is loading"
	#The second line of text under the app name
	state = "Game Starting..."
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["logo"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Optimized Oasis Lite is a lightweight Minecraft modpack that enhances your gameplay experience without adding any new items, now with more optimization"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["block"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord 

	[[init.buttons]]
		label = "Download Optimized Oasis Lite"
		url = "https://github.com/SteamWo1f/Optimized-Oasis-Lite"

[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is currently resting"
	#The second line of text under the app name
	state = "by the water on the oasis"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["logo"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Optimized Oasis Lite is a lightweight Minecraft modpack that enhances your gameplay experience without adding any new items, now with more optimization"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["block"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord 

	[[main_menu.buttons]]
		label = "Download Optimized Oasis Lite"
		url = "https://github.com/SteamWo1f/Optimized-Oasis-Lite"

[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is traveling the desert"
	#The second line of text under the app name
	state = "(Combing the sands for others)"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["logo"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Optimized Oasis Lite is a lightweight Minecraft modpack that enhances your gameplay experience without adding any new items, now with more optimization"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["multi"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord 

	[[server_list.buttons]]
		label = "Download Optimized Oasis Lite"
		url = "https://github.com/SteamWo1f/Optimized-Oasis-Lite"

[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is traveling the Realms"
	#The second line of text under the app name
	state = "(Combing the sands for others)"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["logo"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Optimized Oasis Lite is a lightweight Minecraft modpack that enhances your gameplay experience without adding any new items, now with more optimization"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["multi"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord 

	[[realms_list.buttons]]
		label = "Download Optimized Oasis Lite"
		url = "https://github.com/SteamWo1f/Optimized-Oasis-Lite"

[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is joining a game"
	#The second line of text under the app name
	state = "Game Starting..."
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["logo"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Optimized Oasis Lite is a lightweight Minecraft modpack that enhances your gameplay experience without adding any new items, now with more optimization"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["block"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord 

	[[join_game.buttons]]
		label = "Download Optimized Oasis Lite"
		url = "https://github.com/SteamWo1f/Optimized-Oasis-Lite"

[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "Exploring %world%"
	#The second line of text under the app name
	state = "(Alone in the infinite dunes)"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["logo"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Optimized Oasis Lite is a lightweight Minecraft modpack that enhances your gameplay experience without adding any new items, now with more optimization"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["solo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord 

	[[single_player.buttons]]
		label = "Download Optimized Oasis Lite"
		url = "https://github.com/SteamWo1f/Optimized-Oasis-Lite"

[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Travleing %servername% with %players%"
	#The second line of text under the app name
	state = "(Camping under the stars)"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["logo"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Optimized Oasis Lite is a lightweight Minecraft modpack that enhances your gameplay experience without adding any new items, now with more optimization"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["multi"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord 

	[[multi_player.buttons]]
		label = "Download Optimized Oasis Lite"
		url = "https://github.com/SteamWo1f/Optimized-Oasis-Lite"

[realms]
	#Enable/Disable the Realms Game Event
	enabled = true
	#The first line of text under the app name
	description = "Currently exploring %realmname%"
	#The second line of text under the app name
	state = "Playing on a Realm"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["logo"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Optimized Oasis Lite is a lightweight Minecraft modpack that enhances your gameplay experience without adding any new items, now with more optimization"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["multi"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%realmdescription%"
	#The buttons to display on Discord 

	[[realms.buttons]]
		label = "Download Optimized Oasis Lite"
		url = "https://github.com/SteamWo1f/Optimized-Oasis-Lite"

[generic]
	#The first line of text under the app name
	description = "Playing Minecraft"
	#The second line of text under the app name
	state = "(Soon to rest, Soon to awaken)"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["logo"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Optimized Oasis Lite is a lightweight Minecraft modpack that enhances your gameplay experience without adding any new items, now with more optimization"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["block"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord 

	[[generic.buttons]]
		label = "Download Optimized Oasis Lite"
		url = "https://github.com/SteamWo1f/Optimized-Oasis-Lite"

[custom]
	#Must these variables be parsed along with other variables
	enabled = true
	#Your custom variables to add
	variables = []

[dimension_overrides]
	enabled = true

	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = "%player% is in The Overworld"
		state = "(The sun shines brightly)"
		largeImageKey = ["logo"]
		largeImageText = "In the Overworld"
		smallImageKey = ["over"]
		smallImageText = "%mods% mods installed"

		[[dimension_overrides.dimensions.buttons]]
			label = "Download Optimized Oasis Lite"
			url = "https://github.com/SteamWo1f/Optimized-Oasis-Lite"


	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = "%player% is in The Nether"
		state = "(The lava heats your skin)"
		largeImageKey = ["logo"]
		largeImageText = "In the Nether"
		smallImageKey = ["nether"]
		smallImageText = "%mods% mods installed"

		[[dimension_overrides.dimensions.buttons]]
			label = "Download Optimized Oasis Lite"
			url = "https://github.com/SteamWo1f/Optimized-Oasis-Lite"


	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = "%player% is in The End"
		state = "(Exploring the void)"
		largeImageKey = ["logo"]
		largeImageText = "In the End"
		smallImageKey = ["end"]
		smallImageText = "%mods% mods installed"

		[[dimension_overrides.dimensions.buttons]]
			label = "Download Optimized Oasis Lite"
			url = "https://github.com/SteamWo1f/Optimized-Oasis-Lite"



